artifact_location: file:///F:/My File/P.E.2/Badminton-Analytics-Yolov8/runs/mlflow/0
creation_time: 1743167118353
experiment_id: '0'
last_update_time: 1743167118353
lifecycle_stage: active
name: Default
